### ISSUE TITLE
WebGL stats link for standard derivative extension

### ISSUE THREAD

**Issue by pyalot** [rreusser/glsl-solid-wireframe#2]
The link to http://webglstats.com/webgl/extension/standard_derivatives from https://www.npmjs.com/package/glsl-solid-wireframe and https://github.com/rreusser/glsl-solid-wireframe is no longer valid and has been replaced by the canonical form http://webglstats.com/webgl/extension/OES_standard_derivatives

**Comment by rreusser** [comment]
Thanks. Will update shortly.

**Comment by rreusser** [comment]
Fixed, though haven't updated on npm. That's the part that will need to be done later. Thanks!
